### NumPy

Numpy is a fundamental library in scientific computing in Python. It provides support to arrays and matrices along with a collection of mathematical functions to operate on these data structures.

In [1]:
# To install numpy library

! pip install numpy

In [9]:
# to create an 1D array
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
# to print the shape (for a 1D array, only 1 value will be in the output)
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [13]:
# to convert a 1D array to 2D

arr1.reshape(1,6)
# 2 braces in the output indicates it is a 2D array

array([[1, 2, 3, 4, 5, 6]])

In [11]:
# to convert a 1D array to 2D

arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# to create a 2D array

arr2 = np.array([[1,2,3,4],[3,4,5,6]])
print(arr2)
print(type(arr2))
# to print the shape (for a 2D array, 2 values will be given in the output)
print(arr2.shape)

[[1 2 3 4]
 [3 4 5 6]]
<class 'numpy.ndarray'>
(2, 4)


In [16]:
# to create a 1D array with in the specified range
# np.arange(start, end, step)
arr3 = np.arange(0,10,2)
print(arr3)
print(type(arr3))
print(arr3.shape)

[0 2 4 6 8]
<class 'numpy.ndarray'>
(5,)


In [19]:
# to convert a matrix from 1X5 to 5X1
arr3 = np.arange(0,10,2).reshape(5,1)
print(arr3)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [23]:
# to create a matrix with 1's as all the elements
arr4 = np.ones((3,4))
print(arr4)
print(f'Type: ',type(arr4))
print(f'Shape: ',arr4.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 4)


In [25]:
## Identity Matrix
np.eye(3)
## creates a 3X3 matrix with all the diagonal elements as 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
## Attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape (rows, columns for a 2D array): ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data Type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (rows, columns for a 2D array):  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data Type:  int64
Item size (in bytes):  8


In [35]:
## Vectorized Operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## element wise operations in vectors
print("Addition: ", arr1+arr2)
print("Subtraction: ", arr1-arr2)
print("Mulitplication: ", arr1*arr2)
print("Division: ", arr1/arr2 )

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Mulitplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [36]:
## Universal Functions (functions that applicable to the entire array)

arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural Logarithm
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [37]:
## Array slicing and indexing operations

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
## Indexing
arr[0][0]
## arr[0,0] both works same

1

In [49]:
## Indexing
arr[1,1]

6

In [50]:
## Slicing
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [51]:
## Slicing
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [52]:
## Modifying the array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [53]:
## Modifying multiple elements
arr[0:2,0:2] = 100
print(arr)

[[100 100   3   4]
 [100 100   7   8]
 [  9  10  11  12]]


In [55]:
## Statisctical Concepts -- Normalization
## Normalization is an approach to make the mean to 0 and standard deviation to 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Calculate normalized data
norm_data = (data-mean)/std_dev

## Print Normalized data
print("Normalized Data: ", norm_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [57]:
## Statistical Concepts
data = np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean = np.mean(data)
print("Mean: ", mean)

## Median
median = np.median(data)
print("Median: ", median)

## Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

## Variance
var = np.var(data)
print("Variance: ", var)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [77]:
## Logical Operations

data = np.arange(1,11,1)

data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [80]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])