# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [50]:
import numpy as np

## To create array with size 5X5
array = np.random.randint(1,21,size=(5,5))
print("Original Array: \n", array)

## To set all the elements in the 3rd column to 1
array[:,2] = 1
array

Original Array: 
 [[20  5 11 20 20]
 [ 9 17  1  9  2]
 [18 18 10 19  1]
 [10 14  1  8 10]
 [ 9  2 19 18 17]]


array([[20,  5,  1, 20, 20],
       [ 9, 17,  1,  9,  2],
       [18, 18,  1, 19,  1],
       [10, 14,  1,  8, 10],
       [ 9,  2,  1, 18, 17]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [56]:
## To create an array of 4X4 size with random integers from 1 to 16
array2 = np.random.randint(1,17, size=(4,4))
print(array2)
print()

## Approach 1
np.fill_diagonal(array2,0)
print('Array with replaced diagonal elements with 0:\n',array2)
print()

## Approach 2
for n in range(0,4):
    array2[n,n]=0
print('Array with 2nd approach\n', array2)

[[12  1  8 15]
 [14  4  9  7]
 [12  1  3 12]
 [12 12  4 15]]

Array with replaced diagonal elements with 0:
 [[ 0  1  8 15]
 [14  0  9  7]
 [12  1  0 12]
 [12 12  4  0]]

Array with 2nd approach
 [[ 0  1  8 15]
 [14  0  9  7]
 [12  1  0 12]
 [12 12  4  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [64]:
array = np.random.randint(1,37,size=(6,6))
print('A 6X6 Array:\n', array)
print()

## To extract the sub-array
print("Sub Array:")
print(array[2:5, 1:4])

A 6X6 Array:
 [[13 32 16 21 29  1]
 [18  6 24 17 19  1]
 [15  6 19  4  7  7]
 [15  3 30 12  7  5]
 [29 21 27 31 22 19]
 [26 23 13 36 22 36]]

Sub Array:
[[ 6 19  4]
 [ 3 30 12]
 [21 27 31]]



2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [76]:
array = np.random.randint(1,26,size=(5,5))
print('5X5 Array: ')
print(array)

## To extract the elements on the border
new_array = np.concatenate((array[0,:], array[-1,:], array[1:-1,0], array[1:-1,-1]))
## first_row+last_row+first_column+last_column
print()
print('Border Elements:')
print(new_array)

5X5 Array: 
[[ 9 24  9 13  4]
 [12 20 24  2  6]
 [24  1 25  2 23]
 [12  8  2 17 22]
 [ 1 11 15 16  6]]

Border Elements:
[ 9 24  9 13  4  1 11 15 16  6 12 24 12  6 23 22]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [98]:
array1 = np.random.randint(1,21,size=(3,4))
array2 = np.random.randint(1,21,size=(3,4))
print('Array 1:')
print(array1)
print()
print('Array2')
print(array2)
print()

## Element Wise Operations i.e., vector operations
print('Vector Sum: \n', array1+array2)
print()
print('Vector Sub: \n', array1-array2)
print()
print('Vector Mul: \n', array1*array2)
print()
print('Vector Div: \n', np.round(array1/array2,1))
## Rounded of nearest 1 decimal value
print()

Array 1:
[[ 4 13  4  4]
 [ 5  2  5 16]
 [16 14  1 18]]

Array2
[[10  5  1  2]
 [12 14 17  5]
 [ 4  5 19  8]]

Vector Sum: 
 [[14 18  5  6]
 [17 16 22 21]
 [20 19 20 26]]

Vector Sub: 
 [[ -6   8   3   2]
 [ -7 -12 -12  11]
 [ 12   9 -18  10]]

Vector Mul: 
 [[ 40  65   4   8]
 [ 60  28  85  80]
 [ 64  70  19 144]]

Vector Div: 
 [[0.4 2.6 4.  2. ]
 [0.4 0.1 0.3 3.2]
 [4.  2.8 0.1 2.2]]




2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [102]:
array = np.random.randint(1,17,size=(4,4))
print(array)

row_sum  = np.sum(array, axis=1)
column_sum = np.sum(array)
print()
print('Row-wise elements sum: ', row_sum)
print()
print('Column-wise elements sum: ', column_sum)

[[ 1  3  7 14]
 [ 9  2  8  2]
 [ 2 13 11 15]
 [13  1  3  5]]

Row-wise elements sum:  [25 21 41 22]

Column-wise elements sum:  109


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [107]:
array = np.random.randint(1,100,size=(5,5))
print('Original Array:\n', array)

mean = np.mean(array)
median = np.median(array)
std_div = np.std(array)
var = np.var(array)
print('Mean: ',mean)
print('Median: ', median)
print('Standard Deviation: ', std_div)
print('Variance: ', var)


Original Array:
 [[84 77 91 13 80]
 [47 86  5 94 41]
 [55 35 33 33 80]
 [54 96 32 77 73]
 [ 2 65 90 93 44]]
Mean:  59.2
Median:  65.0
Standard Deviation:  28.651003472827963
Variance:  820.88


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [113]:
## To normalize the data, we must calculate mean and std_div

array = np.random.randint(1,9,size=(3,3))
print('Original Array')
print(array)

mean = np.mean(array)
std_div = np.std(array)

normalized_data = (array-mean)/std_div

print()
print('Normalized Data')
print(normalized_data)

Original Array
[[4 6 2]
 [3 5 5]
 [7 4 2]]

Normalized Data
[[-0.13736056  1.09888451 -1.37360564]
 [-0.7554831   0.48076197  0.48076197]
 [ 1.71700705 -0.13736056 -1.37360564]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.