# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [50]:
import numpy as np

## To create array with size 5X5
array = np.random.randint(1,21,size=(5,5))
print("Original Array: \n", array)

## To set all the elements in the 3rd column to 1
array[:,2] = 1
array

Original Array: 
 [[20  5 11 20 20]
 [ 9 17  1  9  2]
 [18 18 10 19  1]
 [10 14  1  8 10]
 [ 9  2 19 18 17]]


array([[20,  5,  1, 20, 20],
       [ 9, 17,  1,  9,  2],
       [18, 18,  1, 19,  1],
       [10, 14,  1,  8, 10],
       [ 9,  2,  1, 18, 17]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [56]:
## To create an array of 4X4 size with random integers from 1 to 16
array2 = np.random.randint(1,17, size=(4,4))
print(array2)
print()

## Approach 1
np.fill_diagonal(array2,0)
print('Array with replaced diagonal elements with 0:\n',array2)
print()

## Approach 2
for n in range(0,4):
    array2[n,n]=0
print('Array with 2nd approach\n', array2)

[[12  1  8 15]
 [14  4  9  7]
 [12  1  3 12]
 [12 12  4 15]]

Array with replaced diagonal elements with 0:
 [[ 0  1  8 15]
 [14  0  9  7]
 [12  1  0 12]
 [12 12  4  0]]

Array with 2nd approach
 [[ 0  1  8 15]
 [14  0  9  7]
 [12  1  0 12]
 [12 12  4  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [64]:
array = np.random.randint(1,37,size=(6,6))
print('A 6X6 Array:\n', array)
print()

## To extract the sub-array
print("Sub Array:")
print(array[2:5, 1:4])

A 6X6 Array:
 [[13 32 16 21 29  1]
 [18  6 24 17 19  1]
 [15  6 19  4  7  7]
 [15  3 30 12  7  5]
 [29 21 27 31 22 19]
 [26 23 13 36 22 36]]

Sub Array:
[[ 6 19  4]
 [ 3 30 12]
 [21 27 31]]



2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [76]:
array = np.random.randint(1,26,size=(5,5))
print('5X5 Array: ')
print(array)

## To extract the elements on the border
new_array = np.concatenate((array[0,:], array[-1,:], array[1:-1,0], array[1:-1,-1]))
## first_row+last_row+first_column+last_column
print()
print('Border Elements:')
print(new_array)

5X5 Array: 
[[ 9 24  9 13  4]
 [12 20 24  2  6]
 [24  1 25  2 23]
 [12  8  2 17 22]
 [ 1 11 15 16  6]]

Border Elements:
[ 9 24  9 13  4  1 11 15 16  6 12 24 12  6 23 22]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [98]:
array1 = np.random.randint(1,21,size=(3,4))
array2 = np.random.randint(1,21,size=(3,4))
print('Array 1:')
print(array1)
print()
print('Array2')
print(array2)
print()

## Element Wise Operations i.e., vector operations
print('Vector Sum: \n', array1+array2)
print()
print('Vector Sub: \n', array1-array2)
print()
print('Vector Mul: \n', array1*array2)
print()
print('Vector Div: \n', np.round(array1/array2,1))
## Rounded of nearest 1 decimal value
print()

Array 1:
[[ 4 13  4  4]
 [ 5  2  5 16]
 [16 14  1 18]]

Array2
[[10  5  1  2]
 [12 14 17  5]
 [ 4  5 19  8]]

Vector Sum: 
 [[14 18  5  6]
 [17 16 22 21]
 [20 19 20 26]]

Vector Sub: 
 [[ -6   8   3   2]
 [ -7 -12 -12  11]
 [ 12   9 -18  10]]

Vector Mul: 
 [[ 40  65   4   8]
 [ 60  28  85  80]
 [ 64  70  19 144]]

Vector Div: 
 [[0.4 2.6 4.  2. ]
 [0.4 0.1 0.3 3.2]
 [4.  2.8 0.1 2.2]]




2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [102]:
array = np.random.randint(1,17,size=(4,4))
print(array)

row_sum  = np.sum(array, axis=1)
column_sum = np.sum(array)
print()
print('Row-wise elements sum: ', row_sum)
print()
print('Column-wise elements sum: ', column_sum)

[[ 1  3  7 14]
 [ 9  2  8  2]
 [ 2 13 11 15]
 [13  1  3  5]]

Row-wise elements sum:  [25 21 41 22]

Column-wise elements sum:  109


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [107]:
array = np.random.randint(1,100,size=(5,5))
print('Original Array:\n', array)

mean = np.mean(array)
median = np.median(array)
std_div = np.std(array)
var = np.var(array)
print('Mean: ',mean)
print('Median: ', median)
print('Standard Deviation: ', std_div)
print('Variance: ', var)


Original Array:
 [[84 77 91 13 80]
 [47 86  5 94 41]
 [55 35 33 33 80]
 [54 96 32 77 73]
 [ 2 65 90 93 44]]
Mean:  59.2
Median:  65.0
Standard Deviation:  28.651003472827963
Variance:  820.88


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [113]:
## To normalize the data, we must calculate mean and std_div

array = np.random.randint(1,9,size=(3,3))
print('Original Array')
print(array)

mean = np.mean(array)
std_div = np.std(array)

normalized_data = (array-mean)/std_div

print()
print('Normalized Data')
print(normalized_data)

Original Array
[[4 6 2]
 [3 5 5]
 [7 4 2]]

Normalized Data
[[-0.13736056  1.09888451 -1.37360564]
 [-0.7554831   0.48076197  0.48076197]
 [ 1.71700705 -0.13736056 -1.37360564]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [121]:
array = np.random.randint(1,10,size=(3,3))
row_array = np.random.randint(1,10,size = (3,))
print('Orignal Array')
print(array)
print()
print('Row Array')
print(row_array)
print()

## Broadcasting is the vector operation when both the vectors are different in size
print('Result:')
print(array+row_array)
## Here, row array is added to the original array for each each row individually, which is known as 'Broadcasting'


Orignal Array
[[8 2 6]
 [6 3 9]
 [9 8 4]]

Row Array
[2 1 1]

Result:
[[10  3  7]
 [ 8  4 10]
 [11  9  5]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [132]:
array = np.random.randint(1,17,size=(4,4))
column_array = np.random.randint(1,17,size=(4,))
print('Original Array: ')
print(array)
print()
print('Column Array')
print(column_array)
print()

## Result using 1st Approach
print('Result')
print(array-column_array[:,np.newaxis])
print()

## Result using 2nd Approach
column_array_2D = column_array.reshape(4,1)
print('Column Array in 2D')
print(column_array_2D)
print()
print('Result')
print(array-column_array_2D)


Original Array: 
[[11 10  2  6]
 [12  4 14  8]
 [ 1  7  1  9]
 [15  5  7  7]]

Column Array
[ 9  3 12 14]

Result
[[  2   1  -7  -3]
 [  9   1  11   5]
 [-11  -5 -11  -3]
 [  1  -9  -7  -7]]

Column Array in 2D
[[ 9]
 [ 3]
 [12]
 [14]]

Result
[[  2   1  -7  -3]
 [  9   1  11   5]
 [-11  -5 -11  -3]
 [  1  -9  -7  -7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [138]:
array = np.random.randint(1,10,size=(3,3))
print('Original Array')
print(array)
print()

## To use functions from linear algebra, we must use np.linalg
print('Determinant of Array: ', np.linalg.det(array))
print()
print('Inverse of Array: \n', np.linalg.inv(array))
print()
print('Eigenvalues of Array: ', np.linalg.eigvals(array))


Original Array
[[3 3 7]
 [3 6 2]
 [3 1 7]]

Determinant of Array:  -30.000000000000004

Inverse of Array: 
 [[-1.33333333  0.46666667  1.2       ]
 [ 0.5         0.         -0.5       ]
 [ 0.5        -0.2        -0.3       ]]

Eigenvalues of Array:  [-0.52079729 11.52079729  5.        ]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [142]:
array1 = np.random.randint(1,11,size=(2,3))
array2 = np.random.randint(1,11, size=(3,2))
print('Array 1:')
print(array1)
print()
print('Array 2:')
print(array2)
print()

## To perform matrix multiplication, no.of columns in 1st matrix must be equal to no.of rows in 2nd matrix
print('Matrix Multiplication: ')
print(np.dot(array1, array2))


Array 1:
[[7 1 4]
 [4 6 2]]

Array 2:
[[10  6]
 [ 6  1]
 [ 6  8]]

Matrix Multiplication: 
[[100  75]
 [ 88  46]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [145]:
array = np.random.randint(1,10,size=(3,3))
print('Original Arrya: ')
print(array)
print()

print('Array in (1,9) shape: ')
array = array.reshape(1,9)
print(array)
print()

print('Array in (9,1) shape: ')
array = array.reshape(9,1)
print(array)

Original Arrya: 
[[5 6 4]
 [6 5 9]
 [4 5 4]]

Array in (1,9) shape: 
[[5 6 4 6 5 9 4 5 4]]

Array in (9,1) shape: 
[[5]
 [6]
 [4]
 [6]
 [5]
 [9]
 [4]
 [5]
 [4]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [148]:
array = np.random.randint(1,26,size=(5,5))
print('Original Array: ')
print(array)
print()

print('Orignal Array to Flattened Array: ')
flattened_array = array.reshape(25,)
print(flattened_array)
print()

print('Flattened Array to Original Array: ')
print(flattened_array.reshape(5,5))

Original Array: 
[[ 3 21  4  6 20]
 [23 15 21  5  7]
 [14 15 13 19 10]
 [14 18  5 22  8]
 [23 19  9 16 20]]

Orignal Array to Flattened Array: 
[ 3 21  4  6 20 23 15 21  5  7 14 15 13 19 10 14 18  5 22  8 23 19  9 16
 20]

Flattened Array to Original Array: 
[[ 3 21  4  6 20]
 [23 15 21  5  7]
 [14 15 13 19 10]
 [14 18  5 22  8]
 [23 19  9 16 20]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [155]:
array = np.random.randint(1,26,size=(5,5))
print('Original Array: ')
print(array)

## To extract the elements at the corners of the array using fancy index
corner_elements = array[[0,0,-1,-1],[0,-1,0,-1]]
print('Corner Elements: ')
print(corner_elements)


Original Array: 
[[ 3  3 13 25 16]
 [ 4 23  8 20 16]
 [14  3  4 21  2]
 [ 3  1 23 23  4]
 [15 12  3 22  5]]
Corner Elements: 
[ 3 16 15  5]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [162]:
array = np.random.randint(1,17,size=(4,4))
print('Original Array: ')
print(array)
print()

## To set all elements greater than 10 to 10 using boolean indexing
array[array>10]=10
print('Result: ')
print(array)

Original Array: 
[[12  9  7  7]
 [ 9  9 14  8]
 [10  5 10 11]
 [10 16 13  4]]

Result: 
[[10  9  7  7]
 [ 9  9 10  8]
 [10  5 10 10]
 [10 10 10  4]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


    What each part means
    ('name', 'U19')

    Field name: name

    Type: 'U19' = Unicode string, up to 19 characters.
    ​

    ('age', 'i4')

    Field name: age

    Type: 'i4' = 4‑byte (32‑bit) integer.
    ​

    ('weight', 'f4')

    Field name: weight

    Type: 'f4' = 4‑byte (32‑bit) float.
    ​

In [169]:
data_type = [('name','U19'),('age', 'i4'), ('weight', 'f4')]
array = np.array([('Alpha',25,55),('Beta',22,49),('Charlie',26,52)],dtype=data_type)
print('Original Array: ')
print(array)
print()

## Sort data on age
sorted_data = np.sort(array, order='age')
print('Sorted Array: ')
print(sorted_data)

Original Array: 
[('Alpha', 25, 55.) ('Beta', 22, 49.) ('Charlie', 26, 52.)]

Sorted Array: 
[('Beta', 22, 49.) ('Alpha', 25, 55.) ('Charlie', 26, 52.)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

1. Euclidean distance between 2 points is the straight line distance given by Pythagoros

2. Formula to calculate this is:

        For 2D points A(x1,y1) and B(x2,y2)

            d(A,B) = Sqrt(((x2-x1)**2)+((y2-y2)**2))

    For a pair wise euclidean distance for a 3 point matrix A(x1,y1), B(x2,y2), C(x3,y3)

        | d(A,A)  d(A,B)  d(A,C) |
        | d(B,A)  d(B,B)  d(B,C) |
        | d(C,A)  d(C,B)  d(C,C) |

In [201]:
data_type = [('x','i4'),('y','i4')]
array = np.array([(2,5), (3,4), (5,4)], dtype=data_type)
print('Original Array: ')
print(array)
print()

## Formula to calculate Euclidean distances
euclidean_distance = np.sqrt((array['x'][:, np.newaxis]-array['x'])**2+(array['y'][:,np.newaxis]-array['y'])**2)
print('Distances: ')
print(euclidean_distance)



Original Array: 
[(2, 5) (3, 4) (5, 4)]

Distances: 
[[0.         1.41421356 3.16227766]
 [1.41421356 0.         2.        ]
 [3.16227766 2.         0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [203]:
import numpy.ma as ma

In [208]:
array = np.random.randint(1,17, size=(4,4))
print('Original Array: ')
print(array)
print()

masked_array = ma.masked_greater(array, 10)
print('Masked Array: ')
print(masked_array)
print()

sum_unmasked = masked_array.sum()
print('Sum of unmasked elements : ', sum_unmasked)

Original Array: 
[[15  8  4  5]
 [ 9 12  6 15]
 [ 5  6 14  6]
 [13  6  5  9]]

Masked Array: 
[[-- 8 4 5]
 [9 -- 6 --]
 [5 6 -- 6]
 [-- 6 5 9]]

Sum of unmasked elements :  69


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [218]:
array = np.random.randint(1,10,size = (3,3))
print('Original Array: ')
print(array)
print()

masked_array = ma.masked_array(array, np.eye(3))
print('Diagonally Masked Array: ')
print(masked_array)
print()

mean_unmasked = masked_array.mean()
print('Mean of the unmasked elements: ',mean_unmasked)
print()
masked_array = masked_array.filled(mean_unmasked)
print('New Masked Array: ')
print(masked_array)

Original Array: 
[[9 6 5]
 [8 4 8]
 [8 5 1]]

Diagonally Masked Array: 
[[-- 6 5]
 [8 -- 8]
 [8 5 --]]

Mean of the unmasked elements:  6.666666666666667

New Masked Array: 
[[6 6 5]
 [8 6 8]
 [8 5 6]]
